source 'https://github.com/CocoaPods/Specs.git' 
source 'https://github.com/KinRainModulization/KR_PrivatePods.git'

#platform :ios, "9.0"

pod 'CTMediator'
pod 'KRPublishLibrary'

pod 'KRHome'
pod 'KRHomeCategory'

target "KinRain" do
end
